apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: apps-postgres-backups
  namespace: databases
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: nfs-holocron-backup
  resources:
    requests:
      storage: 10Gi
