---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: immich-db-managed-cred
  namespace: databases
spec:
  encryptedData:
    password: AgC7q86vO1gEsm+YRTrkLdq+zR8r1QnZjyhU6690wJ/RxZiYb3ZJDXxk4bpfShkWKs6aP24ZMl+CN59QH9mqyXgGYUEPTuthKXsKhryjg9q4UddPTGmnCYzmPAg2AptC9dEPLw8RAC/+y0y37eP9iAR7DltV5Vd0jiql5wWFgmoGP8DvCVAh+A1aVEeFbuOxWn/0NS+io9d1cya3auZ8ucV1dK4fMeVrBiKlYwW788oklUXdLW/H2uOwui+4YFGW8meZL9eYZmd6O0yYhb1MA9stvytTXwIcrgHkvbCf5PTFlVSVTWzJNmm2rvBELW+Pr/cqrUela16cqsk3OYEctz7cgmicZwcw9NWrl42B4w3t6chDVeWIKgxn6GSBtXutuzaUy/S4/T5q6QXk/DQjQ+tUkbKdlCW937PrucIaNAuLhMsz9opPANTfqJyKUQ12manU4syV7bcTRsnBNRQUWg8+R2SBxJjU9jRf4BII0GhmB03Ht2PnVF+pNNB0Rf+buEmggx0b9VvAjr3UKp5BY/mlNwJPDWarNhiFFAQjhOuZbRXb0gx9om8oBIvb+uHWMJmph+GzoxhJyWytxMJOg8cZz5JYy+YBw05G/CY+ewULDLroDsogs0UlJPfzFAoVU7p1t/r3OZs1uXssF/zhnFNVH/Rf4S++voFG4vuQAdFR6tbRzvGHzmAxSXN0iQseMo6q4iAfbHRS9gkj7O0KJmYN
    username: AgB22pv0dZ/GyG0yi95oBRi5PYTSnqYrot4IFcHeXhSb0PSux6HE7IieyihSV2DRjpc7nwd0c7+W1Z/+bECj0xf+ZMXqk4KkoHlmpgHD0zn9neJ9r7DHcUlEMtAK3L/eKmCWJVhk0ZVO0Jw79Vj/UPAd0P1aKI19ebbL0xvHfaadzJQ7loWt+Da+0zPiavrCHrIq6i8rY2WCpkpE0FF6H9p1rJ1imQCz6i9DtxeW2aqXdAeCe58i9/kiK38YmGldSFv5vkVLASPAAMK5YrNt2/lu+UXUF03hRNSBmasJ7dWt0Lm0hebAZu4lKt5WkNSL3Aud6fBcwncTSMjyKR9jHSKyIBbcl1U1nBYDK3WHrC+ram5SWN2oV67O3qgER5vdGoEW4YLH+kulWpf1iz/stE/4CEx+ALSXgDa54kMiccr+KzDCyOq96e7rIuRc4JZ9K6jbIcD6lZXugG+7bogwGkRLfF9qe5yCfrXArNSpBAiuLITSYn10wbQf8oUQtJ0i/DHsDLlwP3fmyssNBHeQLH4REzsLLUfIhuoeQScD+XrHOPdHAyz0lesmUufAKMkpJLVy61FMaQysz2oGnzzKPAsX2c9/SrF09UYVxps8vrsfPhXfC1o3CPiXTYa7WMBoNJE6s5WkX+oZxMceVbaPhuIGX3+FjXgekabbVJzksEYx8VTU8VLv0Vd9Dl7XXCDzRMYKa9lTH8I=
  template:
    metadata:
      name: immich-db-managed-cred
      namespace: databases
    type: kubernetes.io/basic-auth
