---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: infra-postgres-registry-cred
  namespace: databases
spec:
  encryptedData:
    password: AgCIX9oCPfNNHH+pwLthP6ZMPjialqvqyhVWhrlUP0n/QHGasdHDeSGwxhcBp8ZKslhlm6nX+htwDWile8Vf6WLiFKwbKNjSLm5RmJBeUVi9r823xK+K6l3mWdrRtr5j3Ln4qHRbXDIK8cEfbIE14ACzEa5gwiZPTqn5vMbvoLt1D48vnrAYHdr1VxuJuK9a16g3hSKWzhUoi8lB93x+cj/bMAV2AIYrMHIKG6yPVL1r47r74D5fNnWBQ4DMbbq91/giHvnFOvK5S6dWGrGQLuVnXKjf5l0YFvnfqatjJdcisVJ3sLdiP32fWPrhjsZ2Npy44xQ3m1mCJsca1GiPufw08FKqSjU/ifHS6hMg3k4GkS1o2znhrgBq9OMWNwFccg3RlaEtOZp6qIdcBAZpRZ9NUVeyWrZO/IzSmZqAzqXfnlKGjnZpd4wfZ4AHR32N72L/0o9o8+NAm66glIAz8JOuS/aIP28bNJeazxpLWoGKEMiYQ903weot33Dz2uSYFzbjeIxqhQzBmnjCeQ/d43/nNumXcqzIDOVtfyChQXF/mnP634M8Z+l1JUKJR1UP1/lXmOBuuHi0onVIUMBJCHvIBFqWDD9DN9iNT6uVKXD7uVrMT7d7WjnR+Iz9xghQ4IKX9WIa8zbdItgoTmI41WqsVDpDlLqPd+STdgjBHQS0eg9BpDnVyYQDTSRZk/UewO8GX5sQxmTjWweLaqg7o+L9NeSB6EhRklH4QSUcMYTjoIziRUt8ga+PS187aYtO/Ew=
    username: AgCPHs9Fnz1S1MmAix60YjP701ZVuE7WYt24pwRV7qLUWhzUVPCxr/HvDRql61VR8yLOPhwYpQNfiLh1AVDCTaDNCqhZZS6cdKKqboWzLfB1FyftcnXkREX7PkCPcKj1e4j2f559c8hgAmWPWSJo8rqdOqaebe8ER5REdVVqQw0noOxb0a5EFpqSualEEubVkW40F8g7DuALiUEhq9jGbf2TWhqijU4HbrpgRTsEO6qI1SrNOZ/XdZieEoT13NMMnu20ZVlUj4vI0jwsEugTMvMvm8jEATuWLoZjAQRGoExy8zoIyhceRSD6kAqOWM+bahJhBwAKfq4EUug5l1ljZGLb9z0QqYjCnVB56f+uArgl2WpR0Ut8aaYrOY90gdE4CoytywSFl61468n1DBZqTmhrQbrTdNF097+AGm/8ykY7cYOy445sOI7Ye+Po3oLFrpLCxx5G+n6Zi8kBd3R4YE1FX3XzSivK1dISbHmOkfyGf8fONHfO4TTuJrLLXUwR69T0vf+qNJcUngSo3ed4F6WClcgN9t4RlE7kVx0U8A+jM1YSh+J8vdoxwUYlwonz3vjs5mN7Ey/oVQfW9WhhusQNrQld7df4wqT+HYDfO+Zg1GkL/dxHoxnue2q2ufWN1zkVVoQESB1AvO2gCVR5QV0bvDt3BFoP1qkZHeQGwQXCIyD9377ygmaz48UnvzOuaZtmy6nKhHzTWQ==
  template:
    metadata:
      name: infra-postgres-registry-cred
      namespace: databases
    type: kubernetes.io/basic-auth
