---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: infra-postgres-registry-cred
  namespace: databases
spec:
  encryptedData:
    password: AgBUjra2viSYrBVn8ZPNbm51OMzNGe0NxVzLpII01om7Afyzy/RxMlpcXZmCGgzCbNpi7DWJx80gs4xdSIW8HoZ1RkXZGenzIMbHevLodyLQhJQJr88aTVl95TA1BGNhTTrZYlX/+n2/JKXkpL1DeRMTjozv5hUNTuWPp7RNyqrxXhRcNN3hWfFe2+kClKG9zoKtmUoMuTDATwNiczdMdIx3hW4toVyrqR4ubwGrUJyXQj53q68FVJTdfeyZ9c0AiXyIOiA6D2eOeIOQk+R1QVxLnXMIyjXPqJuNmVx4IGh7ENOxAYBHXEpcdq/WsxSciWv4H6YLWPCQCPmvZ3XUZLRnyTAcTtwfHK/IGRzgr0RB9yxLG/Pn+zo27Tc1+tKshpDUfe2WgkG1Lq+697u4457rMBZQIuxDR8WDvucGUc632ToCCZVuzc5PS+gcnOoXGMuJfKgTlxI+99t6fduBY0gFSFjUWbYBQE8oFLzlNGghuXshbSrQTv7bnXVf/6OWMCYDt8Vg+Se4NVQcljDH7pmMH4KDKp2L9IHi8eb3f1CMZpfSNtqRsa7iVcB08FnlkE31d+rmCQDCDWMgSqFPDa881k7IhUWhrif5ASJSpc+KPQJZLPtXwjiMkj+bc4Bj806NSB07qEiG2Md1jHSG7MTMoTQQ6xgGqxAgsTdls8l++uY0RbI9FOVwzalUfvSHX1WvN2fT7GhW+oflZWi7HVfe1iUySue26kwqNXB+SzSVZbzhKp+GwWB8lvDJMN0OEeA=
    username: AgCko/pQoDWC8xVcLGHK+TS7a9ia8ijj9geNyJx8XrK2xPxiTfMWv6Iz/PxqTou8Mz2YzgjZ681DtIxAVJ/4WUx1KJDwvsi3UCHGiktr4yfA/QZXW0T38RimGH2sRBSGXYuSBEwg3Uq87ZY/Oz8cKMrtgUKn+fmti1uAGGdJWj3Y3jD5FIU0zuU9PwKh2pGxXfcBrKkgIkxxpTR+l6IVYgAHRl5TEMS/XcBF0dQDeYkEKa2ZEbhDov7Ahzp28nzRC3QR5tRZofbmvnzOOVLjFG6DTAuxz8VyIfpONDdVkrCtW1Rx7h1EXKbSpzUxlejkWHNRJokOef7lnkPccRJMt2/xLpEL902RBt6jP8WgGzmohMPeGTRcKvvS2TO7euudrrxJz2Stn5AKWgqaAMK26Z58+CK8sQ4nKInjRVSw98dKeqa2N2rF1WLbeIxT9h8GBlrTJ4fQX+tAAiiAyKScMif6PhZAPLKUInY3lXReoS9QY1srkTXMz8rzYpWBk8J1/ITzuyHJaWIPQILIfZ40qc/dn+RVDzcerOr5QVtM5K7O1FaNJPEXjX3p6XlBh8SJobqXQ4itaUvU1PTWZVIz1Q8NGXRnXIaPkMkIwDRMgye8lkLvFxZ6KE4dNynVKk+tF0hG2ZUkz6IUCSXL50XBBJU60LLwuYRg8zNxtQU1BqirQL/4fIkO2XYBgvkivAa1/5WJm50xWu8gmQ==
  template:
    metadata:
      name: infra-postgres-registry-cred
      namespace: databases
    type: kubernetes.io/basic-auth
