apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: databases
resources:
  - ../../base
  - apps-postgres-cluster.yaml
  - vm-source-sealed-secret.yaml
  - backup-pvc.yaml
  - backup-cronjob.yaml
  - immich-postgres-cluster.yaml
  - immich-db-managed-cred-sealed.yaml
  - immich-backup-pvc.yaml
  - immich-backup-cronjob.yaml
commonAnnotations:
  app.kubernetes.io/instance: korriban
