---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: apps-postgres-vm-source
  namespace: databases
spec:
  encryptedData:
    password: AgB5yDngt6+qEcgQvhMQ0WvnNpejC4Fc5bJGhPr5KX+DFWQc0cOUIYO0EUkHL2o1IpIvmjr3R2FZa9iQGyiDd47Kk30y0FQB3lwuBw2H1JAk7A8BW1QaPwOQP6lHjTRgHTpo2FMTFQTOHS1qI+9L/ed/fqIPq3UX9NTwcADI1qKGFrTYoTDzTVoRti0YmdyJkF4mJZzp070JIfnlVdluIF3lfnmYobWqIOJspRAihY061icqiw1x5hw37rDyCVYbHf6bO2oGjwwtAl93O0W6qO36AlpmPfoF48GjmmxzJ+bfiCanTdOwW77LdNeIaZPo6o63RHr9968IJ6wAB3yScRwdNWjRjhbRDiyD1Fa2Bz1tbclG4AP6r/Y2Kjla3EVomVwTAWJEpg7HL2ptdd19YfKB6yTvksglOOoRGkblSruHXzFhxXWWG+Srp/2Vk3oiicgWzf03DIMbcc88pM+RVenZGrl5XqeiHt98eoLTu8pu9gwWguHMOli6V/zLX5OWI1rdHWjlRlgt+79huO5tupbmNjOUJOtOR6tb1rBpkeBor3vYI+yMNxwECi2V9l6V23WtWI5czJyRZYbn5Gr8W50wyQ+xiCDHjnqMkgbZu9K+gd11vKq6mF6ZGViYzSMzJVtXNcMhjnb3ubYDxtyRvf9mATqvHrBn7/J1tE11udtBkI4FE3VZF1LTLNhjd0XKCpNd7g5zycfU/WBZavKNJaa/
    username: AgC1HdXSkvSI1lglKn7Dv/xk4wBLgMQTJUfBWIUXtYRwHpLnHP1hTqHhuD+52hXsO3Df05wK6yLYYhJqFlW27p4vHDmD+QufuY+515l9uzQsBLByYdNWSnFlX6lUm5d7moCDuPbsZ9MINpSNOhH3UjT8edLuKipRrvdOcXh5w7AGeUlVhYoE3iLX5MnuWSjtK+1Dk7mLS86CouuK2DGnU6wmYhPDnWcKFBdV2ZGhL30GdSgDXQLmUynU3sjxAeM7yabniIJ5jjXzBKXF0Nz3eGT+oIScZNXW+Wb68R/UsCHjxqz/TFgUz9vkRnYmE0Z08u0n9QlsEC1qGkBDPOU2EFfdI/iukBKQCbznfJ0l+2ENcMLs7O8b1TL1KJPC8mFCJENQWLdn1klvmez9R761621oLyqxAwJ6ByYmfYlAOMvRi73VB4iIUhziDWx6jhzY/PVU6R1crZ5I6EtTphHVKlrmFcTp4pbP/Kvdg/Z+wzHDa0kKTFdngViYVO7jcBmVYGN/L4VpXWZmiCfMk4TkgEgf2S73MKT/nXm3FFlPLwuLxmVDwwprLUmZdmi2Q0TIL1oAkswpkPQ9KW6Okm0HFqa+9GMGL0+t4k0LDJ+luT6ZRLXu8d74DtScLr12gyoOnZPgpkOp4yRJVt/Xogzan+4nHvX8VJtQcjKAZH0LkQya6QPYmAIboOC+D5wZbfImmIRBffKMGQ/+Tw==
  template:
    metadata:
      name: apps-postgres-vm-source
      namespace: databases
    type: kubernetes.io/basic-auth
