apiVersion: v1
kind: Service
metadata:
  name: alertmanager
  namespace: monitoring
  annotations:
    prometheus.io/scrape: "true"
    prometheus.io/port: "9093"
    prometheus.io/path: /metrics
spec:
  type: ClusterIP
  ports:
    - name: http
      port: 9093
      targetPort: http
      protocol: TCP
    - name: cluster-tcp
      port: 9094
      targetPort: cluster-tcp
      protocol: TCP
  selector:
    app.kubernetes.io/name: alertmanager
    app.kubernetes.io/component: alertmanager
