apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yaml
  - daemonset.yaml
commonLabels:
  app.kubernetes.io/name: intel-gpu-plugin
  app.kubernetes.io/part-of: gpu-infrastructure
images:
  - name: intel/intel-gpu-plugin
    newName: intel/intel-gpu-plugin
    newTag: "0.31.0"
