---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: harbor-database-cred
  namespace: harbor
spec:
  encryptedData:
    password: AgDA5/z8WxYSo80ZrvlJCtZHUmR1OlK1moPP/wain/UPgrsv328bLgVbqewWAgsmOzn2eEbJ40+XzncxDFRAOXh717ucWJUcXZ8cm08F4x3O6/B2cuNUeLaEIW11/lDMMzRov67gEmYJ3ZEm80bXd5OsnGRjQ4fWhvCsHg8sXY71y/E/4SHYNsQiVa82ptuAX80oXCoPaYuqeNsNCWZeHhAGwmq+JxoQFSnCCyWbtYrQ7s3zYJzPUy7jR3x2lwMBZRyE42E0ybtz+ShxzBtOuyXnU4ZN8jPhK3lrz+MzzkiA2Itw4Oe+bqWidQYIbIT8K53XrBmdKarMX25HjqfzVkYUOtiimmwIBXCIJbeStTOm79kCsUH++SI8hy+NosA/ciTYjZj4P6hZKGsncB+iepbKiqLrCSgBkv+1D0AfZyBF3ukEL1W7W34V067BIJ3cFdR9zLzAG+YpcNLKgHJwTQqcB44ZFWqg6js1wfmrh0O8pD0gonP1tRYBUBsGdMD6vLPQOX26AgC3Wlgw5QdeVthgC8EaZxeL0Il31DOfM8g8lWo23ujQDs3pNGyqhGdREt38cw1uGsIPjTGZMsCLx9wJwsp9HSszGKaCtRp3QB+iVhwhUVLPkqw1fSR30js29ACRx8rTbaZqoZriFHoB6FJyXsg8LmTevI2IWAsy0jwUZIlSYilblu+Xna8tf71LEkODJyyOSNq0t71UQnBMTuSuRhdnCYZbmvOgbcDnQ2oEH35VUhcqr03stTYOy+SWmB4=
  template:
    metadata:
      name: harbor-database-cred
      namespace: harbor
---
---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: harbor-secrets
  namespace: harbor
spec:
  encryptedData:
    HARBOR_ADMIN_PASSWORD: AgAaPHVF3vInkKp7RaWqv8d02kGocl30FrIH6vcKHQNZjoRRHaLx3BZzfaJN1tBQ75z1+5U8lwwQYeunm2/mjbfZY+94cVVwoJzpIBb2DeMclaYZYB9ORm6PDp6eaoCbuo98cIOBTlx/FHd6zX3Rz9Q9tHaK4dUcris6tFAkxX+PmAVwKksIE8aIrb6OhVcsUrwrDJNPeGxVGe/g7VhcnUDM+hNbHJzzQsUdRn3ghr53iPN18PSzrgHiJRaQxGV4aeWEuEPGMG0g4RS3GxN52TOakzS5gFEXTWTZltGL6gxQ2L/FyyTBCJqOq4PvS6IAwWR1zQuYeKLQHVukwpBGI8AGSgvIT2JC0gjn/L6sxLWJAKfJUHffiP5NuWQlYRjX3pYxVAK1OAOT79IBlAHcj2W8JczzWLSbXcmNOEx3+/DRzkBnjhJ50v2o2KsSkSUX4/bQ2SB5Dy+5ZS3qVXqRdIpg1CZ1K+kUmECMCU4AN2bDOt5L0RhEUKCYfvd2N6us/NIaII5vjfx3GWZIv85EFaQQcna9LIZKGqnku//r3QXhUs2V3qci4nDTkEPy6Ro30sQVKiO6o2Cevfrzo25vTPcF81FQinj9A/FsNeT8ieRJ95iEw4XQME4v3zNV+RQa4PSGKkMDkx2Qis+JXcIsq1ml25zgB/JsT6ppzFzmlCUT2QLsz2Sfa9fmSXgVxLUdRwFyhtYwJtuvEguRMJhsA9xxfd978UzoRyaRXx85HIVYIg==
    secretKey: AgDoo/pCEP0ud7XC+K0SUft2OXqDPdqMAxAfD+fW6ylCvlOUf8NqGb48kjkX79nzTPkHt44kZxXPUAE4FmUYCP58XlCqDG3+ZBg/AY60Qs4cPAqu5CHqULzg8xp1mvIWCMYWtc1ameXj7LZFnd6qA1fWJQb+1hkfudYjc54tml3uZ5RqphT2JQO482FMtkzRoytV+DeDRZrI5c9tqmfefm/8zImzsnGZJx957Q4uHItAuT/DAyTvOxmKM3LPIFpPtzHib6+c7gycjhEZmYq1FEScB1vqt66cILtnqqFM8cPJhbr0hBgveyH9CR63CUo3FqymdYOxQYOM3h/uu+4wt1Pf6vnaVxqLWPxuhrseD2AAcYQpyKQFZHkc9B1gceopBvDbg22LF0r8gDieiBTo5I4IHjojjFT6q42lpGEspwaLtlulHBWo2Eq3YtzlhEiTkvqIT3s/9OM/vaBevBrEILyXEoBMiM7mgm/MHr8K6nXQkdF8f+FUSN1UafAaaqbG0QLGZLuEFPxvvgB12B0rYUdfa8Dy/kyr63vFqPrJWFIAXZqfgBNb1OznvheCGmudjEL+Wc51yoHRH1lFg9x0Wikz3c7Vxu54Ow0GqSbHL5O3A+rG5kH49sPB0pYPM60R4+r319kleJX3piiQGmdioeJukJV3+MgOVFdHxMw7YdDoqoGGO2hJY63EPkmPiujrI/TmDGjpFeKjGMAZhjucivfc
  template:
    metadata:
      name: harbor-secrets
      namespace: harbor
