---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: cloudflare-api-token
  namespace: cert-manager
spec:
  encryptedData:
    api-token: AgAKzeu3WrTwkFBsSjFPm7hwHN+BcieaOTByGWNAISmrtrsfZ7dADGlfaP7KfxP3BIACbcZEouYb3HC+r12DIQSQlyO5hzbtrWH7Ogj2+XLLanYMBSvEjW3VapUYtt+0hvgxh4/fEwJ7VtDtG2/ic1L7D6aDa/S29+JeIyAoQJG/MomBs02gkX+y+RIUIXofH4x5Q6GDQ+WRGXdgXvgCa+S76SUBrrJ04TD58GBi2Ad/6FbCak0370QJQ4XOiPcAaNkOMrEdYERtSTVafspa0w7aa1xJM1WYoewySrpXSt9qtO6s8lcWMLRUq2dUHlMepUbnTcusvdFomd3uiMn2WDnh6NwiQMrESPQtQ5/uEvwxKU82FikvyXNha+8+4VlevxXfL77EeE+8MxtV4eNFk7bk5n4vL5+lfb/ETGG+E7xe7JaRpbIkoScmCJ8rleO9LBuiu2raoBSGYkw4g13ILFXmoRHPzCym49CaQNYPJ/B5EZmR3R0xUgkx75BTZ+K6h1oq03QYw/rpHcVR/zTrRv/xKjU2SdDNGntT2xrW4Iqo6cSSpfP8ElLOcwZbu0wZA5mSBEbcEWK/58l/7KiemL0Cqb6Bg5BFnkVsYtM4FKgKz2TSZJr98S7T4sueGfPPomJA8/2mOREl2ySoRNqDEbB3/SdVCysp5juPmVWxuvrEQbs4+Nn73wJm40+PPOlNmXGITsu6BEL4rkZMVEeybJh4zDrKsR4YO4WAxnqdBEHAV/fj/lZ8wHIlrvEZL7TtHgS02SqPPg==
  template:
    metadata:
      name: cloudflare-api-token
      namespace: cert-manager
