apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: harbor-valkey
  namespace: harbor
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: nfs-holocron-fast
  resources:
    requests:
      storage: 2Gi
