apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: harbor-valkey
  namespace: harbor
  labels:
    app.kubernetes.io/name: harbor-valkey
    app.kubernetes.io/component: redis
    app.kubernetes.io/part-of: harbor
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: nfs-holocron-fast
  resources:
    requests:
      storage: 2Gi
