apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: monitoring
resources:
  - serviceaccount.yaml
  - rbac.yaml
  - deployment.yaml
  - service.yaml
  - servicemonitor.yaml
configMapGenerator:
  - name: kube-state-metrics-flux-config
    files:
      - flux-resource-config.yaml
commonLabels:
  app.kubernetes.io/name: kube-state-metrics
  app.kubernetes.io/part-of: monitoring-stack
